### ISSUE TITLE
Proxy - external ip cannot be entered

### ISSUE THREAD

**Issue by stijnsimons** [Apollon77/ioBroker.daikin-cloud#116]
The field for entering the proxy external IP doesn't allow 4 dots when entering an IP address.
When my ip would be 10.10.10.10,  i can only enter it like this: 10.101010

**To Reproduce**  

PLATFORM: LINUX
OPERATING SYSTEM: LINUX
ARCHITECTURE: X64
CPUS: 2
SPEED: 2495 MHZ
MODEL: 11TH GEN INTEL(R) CORE(TM) I9-11900 @ 2.50GHZ
RAM: 3.8 GB
SYSTEM UPTIME: 4 D. 02:15:45
NODE.JS: V14.18.2
NPM: 6.14.15
DISK SIZE: 19.6 GB
DISK FREE: 9.6 GB
ADAPTERS COUNT: 415
UPTIME: 4 D. 02:15:40
ACTIVE INSTANCES: 12
PATH: /OPT/IOBROKER/

**Comment by Apollon77** [comment]
Thenk you, fixed on GitHub
