### ISSUE TITLE
Proxy cannot be started

### ISSUE THREAD

**Issue by stijnsimons** [Apollon77/ioBroker.daikin-cloud#117]
error | Error while starting Proxy: TypeError: Cannot read property 'initProxyServer' of null
info | Could not check/recreate proxy certificates: ENOENT: no such file or directory, stat '/opt/iobroker/iobroker-data/daikin-cloud.0/certs/ca.pm'

PLATFORM: LINUX
OPERATING SYSTEM: LINUX
ARCHITECTURE: X64
CPUS: 2
SPEED: 2495 MHZ
MODEL: 11TH GEN INTEL(R) CORE(TM) I9-11900 @ 2.50GHZ
RAM: 3.8 GB
SYSTEM UPTIME: 4 D. 02:15:45
NODE.JS: V14.18.2
NPM: 6.14.15
DISK SIZE: 19.6 GB
DISK FREE: 9.6 GB
ADAPTERS COUNT: 415
UPTIME: 4 D. 02:15:40
ACTIVE INSTANCES: 12
PATH: /OPT/IOBROKER/

**Comment by Apollon77** [comment]
Fixed on Github. Please install again and manually restart adapter afterwards
