### ISSUE TITLE
Status: 3 Geräte im verbundenen Cloud-Konto gefunden, 0 Geräte sind online

### ISSUE THREAD

**Issue by TripleX1978** [Apollon77/ioBroker.daikin-cloud#125]
Die Meldung wird mir im Adapter angezeigt.
In einem ersten Test lassen sich aber alle Geräte im ioBroker ansprechen.
Temperaturen etc. scheinen auch korrekt angezeigt zu werden.
Handelt es sich dabei nur um eine fehlerhafte Anzeige oder funktioniert irgendetwas doch noch nicht?
Der Datenpunkt electrical zeigt im laufenden Betrieb 0kWh an.
Ist das der Verbrauch, der in der App im 2-Stunden-Intervall angezeigt wird oder soll da der aktuelle Stromverbrauch ausgegeben werden?

**Versions:**  
 - Adapter version: v0.1.3
 - JS-Controller version: ???
 - Node version: v14.19.1
 - Operating system: Docker / Linux

Bin noch nicht lange ein ioBroker, also bitte nicht gleich erschlagen falls ich mich gerade etwas dumm anstelle.;-)

**Comment by Apollon77** [comment]
Hi, was besagt denn der "connectedToCloud" state bei den geräten? Wenn da "false" steht dann meldet die Daikin-Cloud das die Geräte gerade nicht zur Cloud verbunden sind. Dann zeigt der Adapter die als "Offline" an (weil er kann ja nur den Status der Cloud wiedergeben).
Wenn Geräte "offline" sind dann sind Sie auch ggf über den Adapter nicht steuerbar. Das könnte ggf auch erklären das Du im Betrieb 0kWh bekommst.

Schau doch mal was die Onecta App zeigt ... wenn die die Online hat der Adapter aber nicht würde ich ein Debug log gern ansehen. Wenn Sie in der App auch Offline sind dann weisst Du was du schauen musst :-)

**Comment by TripleX1978** [comment]
Also unter dem Ordner outdoorUnit gibt es den Datenpunkt cloudConnected und der steht auf True.
Auch in der App sind die Geräte online.
Ist das den der Stromverbrauch in Echtzeit oder der der alle 2 Stunden auch in der App erfasst wird?

**Comment by Apollon77** [comment]
Da der Adapter die Daten aus der Cloud abfragt ist es exakt das gleiche. Leider haben die neueren Geräte keine Lokale Zugriffsmöglichkeit.

Und ja den Bufg mit der Anzaige habe ich gefunden. Update kommt. Danke
