### ISSUE TITLE
Externer Temperaturfühler

### ISSUE THREAD

**Issue by Tombra1889** [Apollon77/ioBroker.daikin-cloud#146]
Weiß zufällig jemand, ob es die Möglichkeit gibt, der Klimaanlage eine externe Temperatur (Wandthermostat) zu übermitteln? Z.B. via http o. ä.

**Comment by Apollon77** [comment]
Nicht bekannt ... Fragen am bestne im Forum stellen, sit GitHub eher ungeeignet
