### ISSUE TITLE
no existing object problem

### ISSUE THREAD

**Issue by homecineplexx** [Apollon77/ioBroker.daikin-cloud#155]
This logs comes really often
Version of adapter: v0.2.3

`
daikin-cloud.0 | 2022-11-04 16:46:20.155 | warn | State "daikin-cloud.0.55e7a364-7327-4512-8cb7-0a0bd1fa62df.lastUpdateReceived" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
daikin-cloud.0 | 2022-11-04 16:46:19.456 | warn | State "daikin-cloud.0.5967fa73-9549-4227-86e8-28415b52ad81.lastUpdateReceived" has no existing object, this might lead to an error in future versions
daikin-cloud.0 | 2022-11-04 16:46:19.407 | warn | State "daikin-cloud.0.9d266deb-004c-4a9c-b70d-17372e1e1364.lastUpdateReceived" has no existing object, this might lead to an error in future versions
daikin-cloud.0 | 2022-11-04 16:46:19.219 | warn | State "daikin-cloud.0.aa4fdaf0-1c6d-4663-8385-51271900f37b.lastUpdateReceived" has no existing object, this might lead to an error in future versions
daikin-cloud.0 | 2022-11-04 16:46:19.218 | warn | State "daikin-cloud.0.aa4fdaf0-1c6d-4663-8385-51271900f37b.climateControl.sensoryData.roomTemperature" has no existing object, this might lead to an error in future versions
daikin-cloud.0 | 2022-11-04 16:46:19.217 | warn | State "daikin-cloud.0.aa4fdaf0-1c6d-4663-8385-51271900f37b.gateway.wifiConnectionStrength" has no existing object, this might lead to an error in future versions
`

**Comment by Apollon77** [comment]
Then please post a full debug log until this info occurs

**Comment by Bens0n68** [comment]
same here - There are no other messages from Daikin-cloud adapter in the log

<html>
<body>


daikin-cloud.0 | 2022-12-07 02:56:55.849 | info | Daikin-Cloud tokens updated ...
-- | -- | -- | --
daikin-cloud.0 | 2022-12-07 02:56:55.731 | info | Daikin-Cloud tokens updated ...
daikin-cloud.0 | 2022-12-07 02:56:55.720 | info | Daikin-Cloud tokens updated ...
daikin-cloud.0 | 2022-12-07 02:56:55.709 | info | Daikin-Cloud tokens updated ...
daikin-cloud.0 | 2022-12-07 02:56:55.524 | info | Daikin-Cloud tokens updated ...
daikin-cloud.0 | 2022-12-07 02:55:55.243 | warn | State "daikin-cloud.0.283e1084-ac2e-4e85-a651-0fb4469cca93.lastUpdateReceived" has no existing object, this might lead to an error in future versions
daikin-cloud.0 | 2022-12-07 02:55:55.229 | warn | State "daikin-cloud.0.915cf2be-f948-49f1-98d1-063b0e1cc5a7.lastUpdateReceived" has no existing object, this might lead to an error in future versions
daikin-cloud.0 | 2022-12-07 02:55:55.199 | warn | State "daikin-cloud.0.285bffaf-74ff-419f-8314-565888aa3006.lastUpdateReceived" has no existing object, this might lead to an error in future versions
daikin-cloud.0 | 2022-12-07 02:55:55.197 | warn | State "daikin-cloud.0.285bffaf-74ff-419f-8314-565888aa3006.gateway.wifiConnectionStrength" has no existing object, this might lead to an error in future versions
daikin-cloud.0 | 2022-12-07 02:55:55.064 | warn | State "daikin-cloud.0.7425a4e8-83ad-469d-82b5-d46c3d5f4dce.lastUpdateReceived" has no existing object, this might lead to an error in future versions
daikin-cloud.0 | 2022-12-07 02:55:55.062 | warn | State "daikin-cloud.0.7425a4e8-83ad-469d-82b5-d46c3d5f4dce.gateway.wifiConnectionStrength" has no existing object, this might lead to an error in future versions


</body>
</html>

**Comment by Apollon77** [comment]
Please provide a full debug log

**Comment by Apollon77** [comment]
No debug log, no help, sorry
