### ISSUE TITLE
ignore state change - not writable

### ISSUE THREAD

**Issue by stijnsimons** [Apollon77/ioBroker.daikin-cloud#157]
Hi, i posted this one before, but i keep on getting these errors..
When checking the device through the daikin app then it's available and controllable, so it's not offline or anything.
Any ideas? 
![image](https://user-images.githubusercontent.com/93920739/201747930-46b940ec-164f-4587-b260-04687c79ca0b.png)

Thanks!

**Comment by stijnsimons** [comment]
I also get these:

![image](https://user-images.githubusercontent.com/93920739/201748559-2bc6e5c2-e040-4a1a-9070-bf21b0beb4ce.png)

**Comment by stijnsimons** [comment]
The weird thing is that if i disable en re-enable the MQTT subsciption, than it works right away...

**Comment by Apollon77** [comment]
Ääähhmm ... the two adapters should not have anything to do with each other.

ALso these single lines do not help me that much. Please enable Debug log for theinstance and post full bedug level logs and tell when which issue or situation happened

**Comment by Apollon77** [comment]
PS: "not writeble" means that on the last polling of data by the adapter the device was reported as offline by the daikin cloud. Maybe this already changed as you openerd the app but the adapter did not recognized that because the data were not polled so far and it would chnage back once this is done?

**Comment by stijnsimons** [comment]
Thanks Ingo. I’ll enable debugging and keep an eye on whats happening. The strange thing is that nothing works until I disable and enable the mqtt subscription. Not sure what the link between the two can be though.Op 14 nov. 2022 om 23:02 heeft Ingo Fischer ***@***.***> het volgende geschreven:﻿
PS: "not writeble" means that on the last polling of data by the adapter the device was reported as offline by the daikin cloud. Maybe this already changed as you openerd the app but the adapter did not recognized that because the data were not polled so far and it would chnage back once this is done?
