### ISSUE TITLE
Expired refresh token requires adapter restart 

### ISSUE THREAD

**Issue by uKL** [Apollon77/ioBroker.daikin-cloud#158]
From time to time, I'm getting the following log

```
Error on device update (2319): Response code 400 (Bad Request) (Refresh Token has expired)
```

When that happens, the only way to regain cloud control is to restart the adapter, which is inconvenient. Is it possible to automatically obtain the refresh token, using the username & password?

**Comment by Apollon77** [comment]
In theory the tokens are 10 years valid ... so seems that Dakin manually expre them from time to time ... whyever ... WIll look into it

**Comment by uKL** [comment]
In my case, it happens every few weeks.

**Comment by harryslapalot** [comment]
I have the same issue. Happens every few weeks.
I temporarily solved it with a script that checks every 5 minutes if the last update received is older than 30 minutes and if so restarts the adapter. Would be nice however if that wasn't necessary.

**Comment by goliat0815** [comment]
i have the same issue and these everyday. The strange thing is that one indoor unit can still be controlled, but the other cannot.

**Comment by RePa02** [comment]
Same issue here and also every few weeks..

**Comment by uKL** [comment]
What makes it even worse is that given the log shows the following
```
60e3f6a7-de7c-4ec3-b96a-8b5836938ab4: Error on device update (22365): Response code 400 (Bad Request) (Refresh Token has expired)
```

the `cloudConnected` and `connection` objects still report true, so the monitoring fails.

**Comment by uKL** [comment]
Hello. Any updates here?

**Comment by FrankSuFra** [comment]
Hallo, ich hatte den Fehler gerade auch wieder.
Wäre toll wenn dies behoben werden könnte ;)

Hello, I just got the same error again.
Would be great if this could be fixed ;)

Gruß, Frank

**Comment by Apollon77** [comment]
Yes I will do when I find time for it

**Comment by Apollon77** [comment]
Github version hat das gefixt ... wie kriegt man das ggf getestet? ;-) oder erst nach release?

**Comment by goliat0815** [comment]
Since the last IOBroker JS-Controller update, you have experienced an issue that has become more pronounced. After restarting the adapter, it works for a very short time. However, after approximately 10 minutes, the error reoccurs:

After the adapter restart: 
Initialize device 247a0f9d-cb71-4e46-8d8b-1ecd96c5f0cb: connected true, lastUpdated Tue Sep 19 2023 11:47:52 GMT+0200 (Central European Summer Time)

Then after some time, only the following error messages appear: 
64760bb7-322e-43ae-ba82-81bfc9098a91: Error on device update (137): Response code 400 (Bad Request) (Missing required parameter auth parameters.)

I’m not sure if reinstalling the adapter will help, but I understand that you rely on it.

**Comment by goliat0815** [comment]
I have now installed the adapter again as another instance. The adapter starts and I also "green" but the following errors appear immediately in the log:

daikin-cloud.1 | 2023-09-19 12:05:54.718 | warn | setObject 64760bb7-322e-43ae-ba82-81bfc9098a91.climateControl.schedule.modes.any.schedules.2 (type=state) property common.role missing!
-- | -- | -- | --
daikin-cloud.1 | 2023-09-19 12:05:54.701 | warn | setObject 64760bb7-322e-43ae-ba82-81bfc9098a91.climateControl.schedule.modes.any.schedules.1 (type=state) property common.role missing!
daikin-cloud.1 | 2023-09-19 12:05:54.675 | warn | setObject 64760bb7-322e-43ae-ba82-81bfc9098a91.climateControl.schedule.modes.any.schedules.0 (type=state) property common.role missing!
daikin-cloud.1 | 2023-09-19 12:05:54.638 | warn | setObject 64760bb7-322e-43ae-ba82-81bfc9098a91.climateControl.schedule.modes.any.meta.actionTypes.fanSpeed.fanOnly.modes.fixed (type=state) property common.role missing!
daikin-cloud.1 | 2023-09-19 12:05:54.570 | warn | setObject 64760bb7-322e-43ae-ba82-81bfc9098a91.climateControl.schedule.modes.any.meta.actionTypes.fanSpeed.auto.modes.fixed (type=state) property common.role missing!
daikin-cloud.1 | 2023-09-19 12:05:54.557 | warn | setObject 64760bb7-322e-43ae-ba82-81bfc9098a91.climateControl.schedule.modes.any.meta.actionTypes.fanSpeed.cooling.modes.fixed (type=state) property common.role missing!
daikin-cloud.1 | 2023-09-19 12:05:54.530 | warn | setObject 64760bb7-322e-43ae-ba82-81bfc9098a91.climateControl.schedule.modes.any.meta.actionTypes.fanSpeed.heating.modes.fixed (type=state) property common.role missing!
daikin-cloud.1 | 2023-09-19 12:05:54.507 | warn | setObject 64760bb7-322e-43ae-ba82-81bfc9098a91.climateControl.schedule.modes.any.meta.actionTypes.roomTemperature.auto (type=state) property common.role missing!
daikin-cloud.1 | 2023-09-19 12:05:54.501 | warn | setObject 64760bb7-322e-43ae-ba82-81bfc9098a91.climateControl.schedule.modes.any.meta.actionTypes.roomTemperature.cooling (type=state) property common.role missing!
daikin-cloud.1 | 2023-09-19 12:05:54.488 | warn | setObject 64760bb7-322e-43ae-ba82-81bfc9098a91.climateControl.schedule.modes.any.meta.actionTypes.roomTemperature.heating (type=state) property common.role missing!

Maybe it will help with the analysis

**Comment by Apollon77** [comment]
Please check again with current Beta version ... and then a fiull log would help ... in fact it is ok when the "error 400" happens once every some hours but should then no longer happen

**Comment by goliat0815** [comment]
Where can i Download the latest Beta. I have changed the repository in ioBroker to Beta Channel but there is no daikin Beta Adapter. Here in the GitHub i can See only the stable Version.

**Comment by goliat0815** [comment]
Ok, I found beta version 0.3.1 and installed it. I'll test this now and report whether it works.

**Comment by staub79** [comment]
Over night this problem happended again also with version v0.3.0
Here is the warning the adapter is sending to the log:

daikin-cloud.0 2023-11-09 06:16:58.164	warn	: Error on device update (1087): Response code 400 (Bad Request) (Refresh Token has expired)
daikin-cloud.0 2023-11-09 06:16:39.485	warn	: Error on device update (1113): Response code 400 (Bad Request) (Refresh Token has expired)
daikin-cloud.0 2023-11-09 06:16:07.812	warn	: Error on device update (1087): Response code 400 (Bad Request) (Refresh Token has expired)
daikin-cloud.0 2023-11-09 06:15:59.669	warn	: Error on device update (1138): Response code 400 (Bad Request) (Refresh Token has expired)
daikin-cloud.0 2023-11-09 06:15:56.584	warn	: Error on device update (1086): Response code 400 (Bad Request) (Refresh Token has expired)
daikin-cloud.0 2023-11-09 06:15:37.938	warn	: Error on device update (1112): Response code 400 (Bad Request) (Refresh Token has expired)
daikin-cloud.0 2023-11-09 06:15:06.783	warn	: Error on device update (1086): Response code 400 (Bad Request) (Refresh Token has expired)

The problem persisted at least for 10 hours.
To resolve it I restarted the daikin adapter which fixed the token problem right away.
See log below:
daikin-cloud.0 | 2023-11-09 06:19:50.966 | info | Initialize 4 Daikin devices
daikin-cloud.0 | 2023-11-09 06:19:50.260 | info | starting. Version 0.3.0 in /opt/iobroker/node_modules/iobroker.daikin-cloud, node: v18.17.1, js-controller: 5.0.12
daikin-cloud.0 | 2023-11-09 06:19:44.025 | info | terminating
daikin-cloud.0 | 2023-11-09 06:19:43.524 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
daikin-cloud.0 | 2023-11-09 06:19:43.522 | info | terminating
daikin-cloud.0 | 2023-11-09 06:19:43.521 | info | Got terminate signal TERMINATE_YOURSELF
daikin-cloud.0 | 2023-11-09 06:19:43.498 | info | Login successful. Adapter should restart soon ...
daikin-cloud.0 | 2023-11-09 06:19:43.497 | info | Daikin token updated in adapter configuration ... restarting adapter in 1s...
daikin-cloud.0 | 2023-11-09 06:19:43.497 | info | Daikin-Cloud tokens updated ...
daikin-cloud.0 | 2023-11-09 06:19:39.596 | info | Login to Daikin Cloud with 
daikin-cloud.0 | 2023-11-09 06:19:39.585 | info | Token seems to be invalid, try automatic re-login ...
daikin-cloud.0 | 2023-11-09 06:19:39.584 | warn | Error on Daikin Cloud communication: Response code 400 (Bad Request) (Refresh Token has expired)
daikin-cloud.0 | 2023-11-09 06:19:37.990 | info | starting. Version 0.3.0 in /opt/iobroker/node_modules/iobroker.daikin-cloud, node: v18.17.1, js-controller: 5.0.12
