### ISSUE TITLE
No adapter start after update.

### ISSUE THREAD

**Issue by MikeEcho0815** [Apollon77/ioBroker.daikin-cloud#184]
`startInstance daikin-cloud.0: required Node.js version ^12.19.0 || ^14.15.0 || ^16.13.0, actual version v18.15.0`

and

`startInstance daikin-cloud.0: instance disabled because of Node.js version mismatch`

I have some issues getting this adapter to start. Does someone has an idea, since the Node.js Versions require greater than... a requirement that is met!?

P.S.: Never mind, just read the info, that node.js 18 is not supported. ;)

**Comment by MikeEcho0815** [comment]
P.S.: Never mind, just read the info, that node.js 18 is not supported. ;)

**Comment by Apollon77** [comment]
PS: next version will remove this because the OpenID lib gave it up to limit nodejs versions without a real need  :-)
