### ISSUE TITLE
Adapter lässt sich nicht installieren

### ISSUE THREAD

**Issue by FrankSuFra** [Apollon77/ioBroker.daikin-cloud#185]
Seit dem Update auf Node.js v18.15.0 lässt sich der Adapter nicht mehr installieren und updaten.

**Comment by Apollon77** [comment]
Ja, siehe Readme ... Bisher war nodejs 18 nicht unterstützt ... es kommt die Tage ein update das es wieder geht weil die eine Library die es bisher verhindert hat aktualisiert hat. Solange geht ggf die Github version schon.

**Comment by FrankSuFra** [comment]
Mit der Katze installiert, funktioniert 👍🏼 
Danke für den schnellen Support :)
