### ISSUE TITLE
Adapter nicht kompatibel mit Node.js 18.5.0 und npm 9.5.0?

### ISSUE THREAD

**Issue by Uwe1984** [Apollon77/ioBroker.daikin-cloud#188]
Hallo, 
folgenden log habe ich vorgefunden, als ich ein update eines anderen Adapters machen wollte. 
Nach dem löschen des Adapters daikin.cloud konnte ich updates durchführen. 

`<html>
<body>

iobroker npm ERR! code EBADENGINEnpm ERR! engine Unsupported enginenpm ERR! engine Not compatible with your version of node/npm: iobroker.daikin-cloud@0.2.3npm ERR! notsup Not compatible with your version of node/npm: iobroker.daikin-cloud@0.2.3npm ERR! notsup Required: {"node":"^12.19.0 \|\| ^14.15.0 \|\| ^16.13.0"}npm ERR! notsup Actual: {"npm":"9.5.0","node":"v18.15.0"}npm ERR! A complete log of this run can be found in:npm ERR! /opt/iobroker/.npm/_logs/2023-04-05T20_13_59_393Z-debug-0.log
--

</body>
</html>`

**Comment by Apollon77** [comment]
es, please see Readme. It is stated there. YOu can use the GitHub version which do not have this limitation

**Comment by StefGuad** [comment]
@Apollon77 was heisst die GitHub version verwenden? Ich habe geraden nach dem Update auf node: v18.16.0 den Adapter über den Github link installiertt, das funktioniert aber nicht.

Gibt es eine Lösung?

**Comment by Apollon77** [comment]
Was genau funktioniert denn nicht?

**Comment by StefGuad** [comment]
Seit dem Update auf node: v18.16.0 kann ich den Daikin Cloud Adapter nicht mehr verwenden 😢
Hatte die Instanz entfernt, weil ich gelesen hatte in deinem Post vom 06. April "YOu can use the GitHub version which do not have this limitation", aber selbst wenn ich den Adapter über Github hinzufüge, kann ich die Instanz danach nicht installieren.

Was verstehe ich da nicht? Gibt es eine Version die auch mit node: v18.16.0 läuft?
![2023-06-05_08h11_44](https://github.com/Apollon77/ioBroker.daikin-cloud/assets/76149512/265ee6ba-7c73-4c64-b60c-d1fccb06f98d)

**Comment by Apollon77** [comment]
Bitte nach GitHub Update vom Adapter den Browser mal reloaden wo Admin ui drin ist. Danach sollte es gehe

**Comment by StefGuad** [comment]
Sorry, aber ich verstehe nicht, was meinst du mit GitHub Update?
Ich füge den Adapter (0.2.3) von Github in Iobroker hinzu.
Wenn ich dann die Instanz installieren möchte, kommt immer derselbe Fehler.

Bitte um Hilfe,
Stefan

**Comment by Apollon77** [comment]
GitHub update: admin, Expertenmodus, adapter, custom install, tab "from github". Dann installieren - falls multihost den korrekten Hort wählen vorher!!  - dann Admin im Browser Reloaden. Dann + drücken unter Adapter falls Instanz nicht schon da war.

**Comment by Apollon77** [comment]
Ja, sobald ich dafür Zeit find und aus dem Urlaub zurück bin tue ich dies

**Comment by gahujipo** [comment]
I followed the "Installieren aus eigener URL"/"Von GitHub" steps. But after creating an instance from it shows me: 
![grafik](https://github.com/Apollon77/ioBroker.daikin-cloud/assets/26710574/4701eb98-da0b-4ee7-9f6e-b5b79be06d72)

Did I make an error? Can I fix that somehow?

**Comment by Apollon77** [comment]
Reload admin UI

**Comment by gahujipo** [comment]
Tried that, but showed still the same error. At the end I restarted the whole container and that worked for me!

**Comment by dans0r** [comment]
Hey @Apollon77 , erstmal Danke für die tolle Arbeit. Betreibe den alten Daikin Adapter bereits zwei Jahre im ioBroker. Habe letzten Monat eine neue Daikin Klimaanlage bekommen, welche sich nur noch per Onecta Verbinden lässt. Somit auf diesen Adapter gestoßen.
Leider bekomme ich keine Instanz hin. Den Adapter hole ich wie bereits weiter oben beschrieben von Github. Auch Browser reload, Admin Instanz neustarten brachte alles nichts. Bekomme nach wie vor die selbe Nachricht angezeigt wie @gahujipo : https://github.com/Apollon77/ioBroker.daikin-cloud/issues/188#issuecomment-1623329281

Node.js 18.17.0 / NPM 9.6.7

**Comment by Newan** [comment]
> Hey @Apollon77 , erstmal Danke für die tolle Arbeit. Betreibe den alten Daikin Adapter bereits zwei Jahre im ioBroker. Habe letzten Monat eine neue Daikin Klimaanlage bekommen, welche sich nur noch per Onecta Verbinden lässt. Somit auf diesen Adapter gestoßen. Leider bekomme ich keine Instanz hin. Den Adapter hole ich wie bereits weiter oben beschrieben von Github. Auch Browser reload, Admin Instanz neustarten brachte alles nichts. Bekomme nach wie vor die selbe Nachricht angezeigt wie @gahujipo : [#188 (comment)](https://github.com/Apollon77/ioBroker.daikin-cloud/issues/188#issuecomment-1623329281)
> 
> Node.js 18.17.0 / NPM 9.6.7

Same here

**Comment by Newan** [comment]
https://github.com/panva/node-openid-client/pull/516
seem it is fixed?

**Comment by Apollon77** [comment]
v0.3.0 just released, latest tomorrow, shouldfix the nodejs issue
