### ISSUE TITLE
Anmeldung der ONECTA APP über Google Mail Account

### ISSUE THREAD

**Issue by manfred-hofmann** [Apollon77/ioBroker.daikin-cloud#191]
Hallo,
Ich habe meine ONECTA App per Google Mail Account verbunden.
D.h. ich habe kein Passwort vergeben, sondern anmelden via Google gemacht.
Wie kann ich den Adapter verbinden?

Gruß
Manfred

**Comment by manfred-hofmann** [comment]
Hat sich erledigt! Ich habe den Onecta Zugang einfach auf Email und Passwort umgestellt.

**Comment by Apollon77** [comment]
Das ist leider der Weg - alternaiv den Proxy weg nutzen (der sollte in einem eigenen Tab sein) Aber USername/PAasswort besser
