### ISSUE TITLE
node.js >16.13

### ISSUE THREAD

**Issue by Tombra1889** [Apollon77/ioBroker.daikin-cloud#192]
**Describe the bug**  
Can't update other adapter while using node.js > 16.13

pi@raspberrypi:/opt/iobroker $ npm install iobroker.js-controller@5.0.11
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: iobroker.daikin-cloud@0.2.3
npm ERR! notsup Not compatible with your version of node/npm: iobroker.daikin-cloud@0.2.3
npm ERR! notsup Required: {"node":"^12.19.0 || ^14.15.0 || ^16.13.0"}
npm ERR! notsup Actual:   {"npm":"9.6.7","node":"v18.17.0"}

npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2023-08-01T11_33_42_577Z-debug-0.log

**Comment by Apollon77** [comment]
Please install Github version for now, after that potentially restart and reload admin to create instance (if not already there)
