### ISSUE TITLE
Schreibstatus ändert sich bei setpoints auf nicht änderbar

### ISSUE THREAD

**Issue by manfred-hofmann** [Apollon77/ioBroker.daikin-cloud#201]
Hallo,
ich habe eine Altherma 3H HT.
Adapter Version 0.3.0.
Normalerweise sind die Werte unter den setpoints die Sollwerte die geändert werden können.
Wenn jedoch das onOffMode Flag auf false gesetzt und der Adapter durchgestartet wird, kann beim domesticHotWaterTank der Wert nicht mehr geändert werden. Das Schreibflag verschwindet und bleibt auch so, bis der onOffMode wieder auf true **und** der Adapter durchgestartet wird.

Meldung im Protokoll:
Ignore state change for ac546901-e9dc-4155-b327-bf32a3e520ec.domesticHotWaterTank.temperatureControl.operationModes.heating.setpoints.domesticHotWaterTemperature because not writable!

Hier der Zustand vor dem Durchstartet des Adapters:
![vorRestart](https://github.com/Apollon77/ioBroker.daikin-cloud/assets/61523485/bf83f68e-c52c-4e16-9a00-c9ec1f1b0d59)
und hier nach dem Neustart:
![nachRestart](https://github.com/Apollon77/ioBroker.daikin-cloud/assets/61523485/862a0c09-0c54-4fee-8bea-8222c2fb8ada)

D.h. falls der Zustand des onOffMode Flag auf false sitzt, muss ich nachdem ich das Flag auf true setzte jedes Mal den kompletten Adapter durchstarten um den Sollwert ändern zu können.  
Ein manuelles setzen des Schreibflags funktioniert auch nicht.

Gruß
Manfred

**Comment by Apollon77** [comment]
DIe Info ob das Feld beschreibbar ist oder nicht wird vom Daikin Server genommen. Wenn ein Gerät in der Daikin-CLoud als Nicht erreichbar/offline markiert ist dann sind auch die Werte nicht beschreibbar. ALso bitte hier prüfen und validieren was das Gerät dort "offline" ist.

**Comment by manfred-hofmann** [comment]
Ja, das ist richtig. In dem Moment wo das onOffMode Flag auf false gesetzt ist, ist der Sollwert nicht änderbar.
So ist es jedenfalls in der App.
Jedoch wenn das onOffMode Flag auf true gesetzt wird sollte der Sollwert geändert werden können.
Das ist aber dann nicht mehr möglich, weil der write Status des Sollwertobjekts im iobroker beim Start des Adapters gesetzt wird.
D.h. wird der Adapter mit onOffMode Flag = true gestartet, ist der Sollwert änderbar. Wird der Adapter mit onOffMode Flag = false gestartet, ist der Sollwert nicht mehr änderbar. Auch wenn danach der onOffMode Flag auf true gesetzt wird!

**Comment by Apollon77** [comment]
Dann brauche ich bitte ein Debug log

**Comment by manfred-hofmann** [comment]
Hier das debug Log.
Aendern des OnOffMode auf True und danach Neustart des Adapters.
Danach ist domesticHotWaterTank.temperatureControl.operationModes.heating.setpoints.domesticHotWaterTemperature beschreibbar!
Dann ab Zeile 169 Aendern des OnOffMode auf False und danach Neustart des Adapters:
Danach ist domesticHotWaterTank.temperatureControl.operationModes.heating.setpoints.domesticHotWaterTemperature nicht mehr beschreibbar!

[daikin-cloud_debug.log](https://github.com/Apollon77/ioBroker.daikin-cloud/files/12598612/daikin-cloud_debug.log)

Ich hoffe das hilft weiter.
Danke für die Mühe.

Übrigens sehe ich auch die Verbrauchsdaten im JSON. 
"m":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,11,14,2,null,null,null]},"unit":"kWh"}
Die kommen im iobroker in den Objekten jedoch nicht an:
![image](https://github.com/Apollon77/ioBroker.daikin-cloud/assets/61523485/cb9730d4-c8b2-4479-971a-e8c2b8ba27bf)
aber das ist evtl. eine ander Baustelle :-)

**Comment by Apollon77** [comment]
Electrical -> Beta Version

Anderes muss ich ansehen

**Comment by Apollon77** [comment]
Ok, mir war nicht bewusst das ein Befehl dafür sorgt das zeug nicht mehr schreibbar ist. Muss ich mal überlegen wie ich das am besten mache

**Comment by Dar4ide** [comment]
@manfred-hofmann hast du denn aktuell einen Workaround gefunden, um die Beschreibbarkeit vorher abzufragen? Ich hatte vermutet, dass "write" vom Objekt auf false gesetzt wird. Das ist aber nicht so, write bleibt auf true, trotzdem gibt's dann den error der API zurück.

**Comment by manfred-hofmann** [comment]
Der Workaround ist aktuell:
Wenn write nicht gesetzt ist den OnOffMode auf True setzen und dann den Adapter durchstarten.
Ein einfaches setzen des Schreibstatus auf true reicht nicht.
Übrigens funktioniert es umgekehrt auch nicht. Also wenn der Schreibstatus auf true sitzt (weil OnOffMode beim Adapter Start true war) und nachträglich OnOffMode auf false gesetzt wird, dann kann man zwar den Wert domesticHotWaterTank.temperatureControl.operationModes.heating.setpoints.domesticHotWaterTemperature beschreiben, er kommt aber nicht beim Gerät an!

**Comment by DieterB61** [comment]
> Aendern des OnOffMode auf True und danach Neustart des Adapters.

Kannst du den OnOffMode überhaupt ändern wenn er am Beginn auf false war? Meiner war jetzt z.B. auf true und ich konnte nichts ändern, auch den OnOffMode nicht (wäre aber natürlich nicht notwendig gewesen).
So wie ich das sehe, muss man warten bis der OnOffMode selbst true wird und muss dann den Adapter neu starten.

**Comment by manfred-hofmann** [comment]
Der OnOffMode lässt sich bei mir immer ändern. Nur wenn er beim Adapter Start auf false steht, lässt sich die Temperatur nicht mehr ändern, auch wenn der OnOffMode danach auf True gesetzt wird. Die Temperatur lässt sich nur ändern, wenn OnOffMode am Anfang auf True steht.

**Comment by DieterB61** [comment]
Die daikin-cloud.....domesticHotWaterTank.temperatureControl.operationModes.heating.setpoints.domesticHotWaterTemperature läßt sich bei mir überhaupt nicht ändern. Kannst du den Wert bei dir auch in der ONECTA App ändern (geht bei mir auch dort nicht)? Wie wird bei dir das Warmwasser generell gesteuert? Ich fahre ein Zeitprogramm.
Was bei mir vom ioBroker aus geht, sind Änderungen der Vorlauftemperatur (+/-), powerfulMode ein/aus, und Heizung bzw. Warmwasser ein/aus.

**Comment by manfred-hofmann** [comment]
Ich kann den Warmwasserwert in der App auch nur dann ändern, wenn Warmwasser an ist. 
Nein, ich habe kein Zeitprogramm. Ich steuere alles über den IOBROKER. Auch die Heizung. Dank des tollen Adapter hier. Die Regelung der Heizung von Daikin ist ziemlich eingeschränkt und bietet mir zu wenig Möglichkeiten.

**Comment by Apollon77** [comment]
v2.0 is available for GitHub test (https://github.com/Apollon77/ioBroker.daikin-cloud/issues/215#issuecomment-2208891591). Please check and verify with this and add another log if needed as new issue. Status should now be preserved when it was online once

**Comment by manfred-hofmann** [comment]
Das Problem besteht weiterhin, aber ich kann damit leben ;-)

**Comment by Apollon77** [comment]
@manfred-hofmann Aber ich nicht *gg* Bitte installier mal von GitHub (gleiche verison, also danach manuell restarten und Debug log

Ich hab jetzt Logging eingebaut was zeigen sollte was da los ist. Bitte mal provozieren und mir log schicken oder hier posten. Danke

**Comment by manfred-hofmann** [comment]
@Apollon77 
Anbei der Start mit domesticHotWaterTank.onOffMode = false:
[daikin-cloud_start_onOffMode_false.log](https://github.com/user-attachments/files/16193299/daikin-cloud_start_onOffMode_false.log)
Ich denke es liegt daran:
`"temperatureControl":{"/operationModes/heating/setpoints/domesticHotWaterTemperature":{"settable":false,"requiresReboot":false,"value":46,"maxValue":127,"minValue":-127,"stepValue":1}}`


und hier der Start mit domesticHotWaterTank.onOffMode = true:
[daikin-cloud_start_onOffMode_true.log](https://github.com/user-attachments/files/16193311/daikin-cloud_start_onOffMode_true.log)
Hier sieht e so aus:
`"temperatureControl":{"/operationModes/heating/setpoints/domesticHotWaterTemperature":{"settable":true,"requiresReboot":false,"value":46,"maxValue":65,"minValue":30,"stepValue":1}}`



Gruß
Manfred

**Comment by Apollon77** [comment]
Ferhler gefunden. versuch nochmal bitte mit GitHub version!

**Comment by manfred-hofmann** [comment]
Der Schreibstatus im iobroker bleibt jetzt zwar auf änderbar. Aber beim setzen eines neuen Wertes geht es trotzdem nicht.
Obwohl ich vorher onOffMode auf true gesetzt habe:
[versuch2.txt](https://github.com/user-attachments/files/16198745/versuch2.txt)


D.h. ist eher schlechter geworden, da man nun nicht mehr erkennen kann ob es beschreibbar ist oder nicht.

**Comment by Apollon77** [comment]
Hm... bitte nochmal Debug log von start und änderungen, vllt sehe ich dann warum er das so tut ... strange

**Comment by manfred-hofmann** [comment]
Hallo,
Hier nochmal das Debug log. Einmal mit Adapter Start bei OnOffMode = true und einmal mit Adapter Start bei OnOffMode = false.
Ich habe ein paar Anmerkungen eingefügt, damit man die entscheidenden Stellen besser findet:
[daikin-cloud_start_mit_onOffMode_true_und_false.log](https://github.com/user-attachments/files/16255309/daikin-cloud_start_mit_onOffMode_true_und_false.log)

Wie gesagt, so wie es vorher war, war es für mich auch ok. 
Dann kann ich per Skript den Adapter neustarten, wenn der Parameter nicht beschreibbar ist. 
Jedoch muss dann aber der Schreibstatus von "../operationModes/heating/setpoints/domesticHotWaterTemperature" entsprechend zum Verhalten passen.

Gruß
Manfred

**Comment by Apollon77** [comment]
Hm .. .also das Log sieht korrekt aus. Der Fehler "Value not writable" kommt von wo anders und sollte da immer schon so gekommen sein.. ok denke war früher weniger problematisch weil öfter die Daten aktualisiert wurden.

Bitte nochmal GitHub version versuchen. Idealerweise muss du auch keine objekte manuell anfassen oder so

**Comment by manfred-hofmann** [comment]
Hey, klasse jetzt funktioniert es.
Vielen Dank für die Mühe.
Gruß Manfred

**Comment by Apollon77** [comment]
Ok, cool, dann kommt das als offizielles release
