### ISSUE TITLE
powerfulMode cannot be set

### ISSUE THREAD

**Issue by DieterB61** [Apollon77/ioBroker.daikin-cloud#204]
**Describe the bug**  
When I try to set the state of the daikin-cloud.....domesticHotWaterTank.powerfulMode, it is not set in the HP

**To Reproduce**  
1. Try to set daikin-cloud.....domesticHotWaterTank.powerfulMode = true in ioBroker objects
2. Value is set but will be reseted after a few seconds by the value of the App (here false)

**Expected behavior**  
The value shout be transmitted to the cloud and the App

**Screenshots & Logfiles**  
no

**Versions:**  
 - Adapter version: 0.3.0
 - JS-Controller version: 5.0.12
 - Node version:  v16.20.2
 - Operating system: Debian on Rasperry

**Additional context**  
I think it worked half a year ago.

**Comment by Apollon77** [comment]
Please post a full debug log of initialization and also such an action.

**Comment by DieterB61** [comment]
Hi, when I did the initialization logs, the adapter restarted (as expected). After that, the setting of the powerfulMode was possible :-). 
Nevertheless I attached both logs.
But I'm afraid, the problem will come again. I will repeat the log if it happens.

[startPowerfulModeFromIobroker.log](https://github.com/Apollon77/ioBroker.daikin-cloud/files/13062756/startPowerfulModeFromIobroker.log)
[initialization.log](https://github.com/Apollon77/ioBroker.daikin-cloud/files/13062757/initialization.log)

**Comment by bakerman23** [comment]
Es ist das gleiche Problem wie #201 . 
Schreibstatus ändern und den Adapter neu starten hilft aber.
Das Problem scheint immer nach einem Update zu kommen.

**Comment by DieterB61** [comment]
> Es ist das gleiche Problem wie #201 . Schreibstatus ändern und den Adapter neu starten hilft aber. Das Problem scheint immer nach einem Update zu kommen.

Aktuell kann ich gar nichts mehr ändern, weder Heizung oder Warmwasser ein/ausschalten noch PowerfulMode setzten oder die Vorlauftemperatur ändern. Wenn ich es in der ONECTA App ändere wird es aber im ioBroker dann auch richtig angezeigt.
Was meinst du mit Schreibstatus ändern? Geht das in der Instanz oder in den Objekten (bei welchem müsste ich es ändern?).

>It's the same problem as #201. Changing the write status and restarting the adapter helps, however. The problem always seems to come after an update.

I can't change anything at the moment, neither turn the heating or hot water on/off, nor set PowerfulMode or change the flow temperature. If I change it in the ONECTA app, it is then displayed correctly in the ioBroker.
What do you mean by change write status? Is this possible in the instance or in the objects (which one would I have to change?).

**Comment by bakerman23** [comment]
Hast du dir #201 überhaupt angesehen? Dort ist alles beschrieben.
Ja, das was du ändern möchtest, musst du in den Objekten schreibbar machen. Wo auch sonst?
Danach die Instanz neu starten.

**Comment by DieterB61** [comment]
Danke, ich hatte es natürlich gelesen, aber mein Problem war, dass ich gar nichts ändern konnte. Neustart hat aber geholfen. Den hatte ich allerdings zuvor auch schon zwei mal gemacht, Allerdings war da wohl der OnOffMode jedesmal auf false (das hatte ich nicht kontrolliert, da ich nur das Handy zur Verfügung hatte).

**Comment by bakerman23** [comment]
Iobroker ist mit dem Handy quasi nicht bedienbar.

**Comment by Apollon77** [comment]
v2.0 is available for GitHub test (https://github.com/Apollon77/ioBroker.daikin-cloud/issues/215#issuecomment-2208891591). Please check and verify with this and add another log if needed as new issue
