### ISSUE TITLE
Additional Data fields?

### ISSUE THREAD

**Issue by indie89** [Apollon77/ioBroker.daikin-cloud#208]
The WiFi Controller with local Interface supplies some additional information (e.g. Indoor humidity and compressor frequency). Is there any Chance to receive these Data Points from Cloud communication too?

Also See https://www.akkudoktor.net/forum/postid/169884/ AS an example

Thanks!

**Comment by Apollon77** [comment]
I can not access the image, but in fact for local interface use iobroker.daikin adapter. for cloud data it all depemnds on which data daikin delivers back. you can post a debug log from adapterstart (taken from disk and not admin!) and check if it is in such a JSON

**Comment by indie89** [comment]
Thanks for your reply. Sorry for not having attached the image directly. Here we go:
![image](https://github.com/Apollon77/ioBroker.daikin-cloud/assets/130271301/8a6af018-c6a3-4584-bd7a-7e3b1e9802c1)

As I have the "wrong" wifi module installed, I have to use the cloud adapter. Sure, the adapter can only display what gets transferred via json.
Can you pls explain briefly, how I can create and access a debug log from the adapter taken from the disk, then I will gladly do this!

**Comment by Apollon77** [comment]
Admin - Expertmode - Instances - expand daikin-cloud.0 - set Loglevel to debug ... this restarts the adapter. grab log from logfile on /opt/iobroker/log/...

**Comment by indie89** [comment]
oh, I just saw, that one of my 3 indoor units of the triple split has a BRP069B4X wifi controller. So I could use your "local" adapter in order to receive cmp-frequency and indoor humidity (all the additional data, I wanted to grab). Should I try to send you the logfiles for the cloud adapter anyways in order to assess if any additional fields are transferred over JSON?

**Comment by Apollon77** [comment]
Feel free.if the data are in they should be already there

**Comment by Apollon77** [comment]
v2.0 is available for GitHub test (https://github.com/Apollon77/ioBroker.daikin-cloud/issues/215#issuecomment-2208891591). Please check and verify with this and add another log if needed as new issue
