### ISSUE TITLE
Adapter did not start anymore due missing fields for Login into Daikin cloud

### ISSUE THREAD

**Issue by MiWoBln** [Apollon77/ioBroker.daikin-cloud#212]
**Describe the bug**  
The login into the Daikin Cloud seems not possible anymore. Logfile report missing Fields data.profile.communicationLanguage, data.profile.countryResidence

**To Reproduce**  
1. Restart Adapter after Refresh Token was expired

**Expected behavior**  
Login into Daikin Cloud is possible and Device is shown in IOB

**Screenshots & Logfiles**  
```
daikin-cloud.0 | 2024-03-08 11:22:00.424 | error | Error on login: Login failed: Missing required fields for registration: data.profile.communicationLanguage, data.profile.countryResidence
daikin-cloud.0 | 2024-03-08 11:21:58.905 | debug | http-mitm-proxy/lib/ca.js already patched to only generate 1 year long certificates
daikin-cloud.0 | 2024-03-08 11:21:58.843 | info | Login to Daikin Cloud with email xxxxxx@yyyy.zz and password
daikin-cloud.0 | 2024-03-08 11:21:58.822 | info | Token seems to be invalid, try automatic re-login ...
daikin-cloud.0 | 2024-03-08 11:21:58.821 | warn | Error on Daikin Cloud communication: Response code 400 (Bad Request) (Refresh Token has expired)
daikin-cloud.0 | 2024-03-08 11:21:56.933 | info | starting. Version 0.3.0 in /opt/iobroker/node_modules/iobroker.daikin-cloud, node: v18.18.2, js-controller: 5.0.19
daikin-cloud.0 | 2024-03-08 11:21:56.265 | debug | Plugin sentry Initialize Plugin (enabled=true)
daikin-cloud.0 | 2024-03-08 11:21:56.201 | debug | States connected to redis: 192.168.1.186:6379
daikin-cloud.0 | 2024-03-08 11:21:56.182 | debug | States create User PubSub Client
daikin-cloud.0 | 2024-03-08 11:21:56.180 | debug | States create System PubSub Client
daikin-cloud.0 | 2024-03-08 11:21:56.167 | debug | Redis States: Use Redis connection: 192.168.1.186:6379
daikin-cloud.0 | 2024-03-08 11:21:56.124 | debug | Objects connected to redis: 192.168.1.186:6379
daikin-cloud.0 | 2024-03-08 11:21:56.107 | debug | Objects client initialize lua scripts
daikin-cloud.0 | 2024-03-08 11:21:55.827 | debug | Objects create User PubSub Client
daikin-cloud.0 | 2024-03-08 11:21:55.825 | debug | Objects create System PubSub Client
daikin-cloud.0 | 2024-03-08 11:21:55.821 | debug | Objects client ready ... initialize now
daikin-cloud.0 | 2024-03-08 11:21:55.783 | debug | Redis Objects: Use Redis connection: 192.168.1.186:6379
host.raspberrypi | 2024-03-08 11:21:53.440 | info | instance system.adapter.daikin-cloud.0 started with pid 25389
host.raspberrypi | 2024-03-08 11:21:53.211 | info | "system.adapter.daikin-cloud.0" enabled
```

**Versions:**  
 - Adapter version: v0.3.0
 - JS-Controller version: 5.0.19
 - Node version: 18.18.2
 - Operating system: Raspberry Pi OS / Debian 11

**Comment by Apollon77** [comment]
Hm ... seems they changed something in how the cloud login works :-(

**Comment by Apollon77** [comment]
Bitte mal versuchen ob der proxy Weg, auch wenn nerviger als direkt direkte Login, noch geht

**Comment by MiWoBln** [comment]
@Apollon77 - 👍thanks that worked for me.
have a sunny weekend. Thanks for the quick support!

**Comment by heikokainz** [comment]
I solved the issue with log off in the Onecta app and log in again. After login in the Onecta app I added the necessary information like language etc. Afterwards the adapter was working again.

**Comment by Bart1909** [comment]
> I solved the issue with log off in the Onecta app and log in again. After login in the Onecta app I added the necessary information like language etc. Afterwards the adapter was working again.

same here. After setting the necessary settings in the login process, the adapters works fine again

**Comment by evilmon** [comment]
same here

**Comment by goliat0815** [comment]
Ich hatte heute den gleichen Fehler und wie oben beschrieben, reicht ein Logout in der App auf dem Smartphone und ein erneuter Login. Dabei wird man dann nach der Ländereinstellung gefragt. Nachdem man das ausgefüllt und sich neu eingeloggt hat, konnte der Adapter durch einen Restart auch wieder zum funktionieren gebracht werden.
Vielen Dank für den Tipp

**Comment by Q7Jensen** [comment]
Wie loggt man sich den in der App aus? Auf dem iPhone finde ich da nix.

**Comment by Bart1909** [comment]
> Wie loggt man sich den in der App aus? Auf dem iPhone finde ich da nix. Ah, im Profil gibt es das Abmelden.

Unten auf `Weiter` dann auf `Profil` und dort gibts `Abmelden`

**Comment by NoPlayBack** [comment]
Internet is cool..
gerade gesehen dass die App nicht mehr läuft, hier geguckt, Lösung gefunden, läuft wieder.
Danke an Alle !!!

Müsst ihr auch ab und zu (geschätzt alle paar Wochen) resetten, weil die Verbindung nicht klappt?

**Comment by goliat0815** [comment]
> Internet is cool.. gerade gesehen dass die App nicht mehr läuft, hier geguckt, Lösung gefunden, läuft wieder. Danke an Alle !!!
> 
> Müsst ihr auch ab und zu (geschätzt alle paar Wochen) resetten, weil die Verbindung nicht klappt?

Ich habe mir eine Script gebaut, was den jede Nacht einmal neu startet.

**Comment by Q7Jensen** [comment]
Alle paar Wochen resetten kann ich bestätigen.

 

Von: goliat0815 ***@***.***> 
Gesendet: Donnerstag, 28. März 2024 15:13
An: Apollon77/ioBroker.daikin-cloud ***@***.***>
Cc: Jensen ***@***.***>; Comment ***@***.***>
Betreff: Re: [Apollon77/ioBroker.daikin-cloud] Adapter did not start anymore due missing fields for Login into Daikin cloud (Issue #212)

 

Internet is cool.. gerade gesehen dass die App nicht mehr läuft, hier geguckt, Lösung gefunden, läuft wieder. Danke an Alle !!!

Müsst ihr auch ab und zu (geschätzt alle paar Wochen) resetten, weil die Verbindung nicht klappt?

Ich habe mir eine Script gebaut, was den jede Nacht einmal neu startet.

**Comment by NoPlayBack** [comment]
> > Internet is cool.. gerade gesehen dass die App nicht mehr läuft, hier geguckt, Lösung gefunden, läuft wieder. Danke an Alle !!!
> > Müsst ihr auch ab und zu (geschätzt alle paar Wochen) resetten, weil die Verbindung nicht klappt?
> 
> Ich habe mir eine Script gebaut, was den jede Nacht einmal neu startet.

Coole Idee.... Ich nehme an timergesteuert mit exec "iobroker restart daikin-cloud.0" ?
Ich lass ihn nochmal laufen und schaue nach ob es da nicht auch ein Flag in den Daten gibt an dem ich erkenne dass er die Verbindung verloren hat.....

**Comment by timoglaess** [comment]
Bei mir verliert nicht nur der Daikin Adapter, sondern auch andere Geräte, die an einem Fritz Repeater hängen, immer wieder mal die Verbindung. Mit einem Script nutze ich die Erreichbarkeit von 3 Geräten als Indikator und starte den Repeater neu. Dadurch Verbindet sich auch der Daikin Adapter wieder. Mir unerklärlich woher diese Abbrüche kommen, aber den schwarzen Peter hatte ich eher dem Repeater zugeschoben.

**Comment by Apollon77** [comment]
v2.0 is available for GitHub test (https://github.com/Apollon77/ioBroker.daikin-cloud/issues/215#issuecomment-2208891591). Please check and verify with this and add another log if needed as new issue
