### ISSUE TITLE
Object daikin-cloud.xxx.cloudConnected not updated anymore

### ISSUE THREAD

**Issue by gammler2003** [Apollon77/ioBroker.daikin-cloud#213]
**Describe the bug**  
Field got updated properly with true/false, depending on whether the respective device was connected to Daikin cloud or not. Since this year no value at all got received, no matter whether the device is connected or not. The field remains empty/null. 

Other than that field, the adapter works perfectly fine!

**To Reproduce**  
Drill down the object tree of the respective Daikin Cloud device

**Expected behavior**  
Updated with true/false, depending on whether the respective device is connected to Daikin Cloud or not

_Update:_
Version of
adapter: 0.3.0
js-controller: 5.0.19
Node.js: v18.20.2

Many thanks in advance

**Comment by gammler2003** [comment]
> Please specify version of adapter js-controller node
done

**Comment by gammler2003** [comment]
> Please specify version of adapter js-controller node

done

**Comment by Apollon77** [comment]
v2.0 is available for GitHub test (https://github.com/Apollon77/ioBroker.daikin-cloud/issues/215#issuecomment-2208891591). Please check and verify with this and add another log if needed as new issue
