### ISSUE TITLE
No object found but 1 Device connected

### ISSUE THREAD

**Issue by tziegenbein** [Apollon77/ioBroker.daikin-cloud#214]
Since 1 week there is no object anymore from Daikin Cloud. Online Info is shown with connected. And in configuration there is the hint that 1 device is found on Cloud and connected. But there is no object. The heating was working correctly and perfectly since half a year. Nothing changed.

Js controller 5.0.19
Node is v18.17.1 
NPM 10.2.2

**Comment by Apollon77** [comment]
Did you restarted the adapter? What does the log tell? Try enable Debug log and post log content

**Comment by Apollon77** [comment]
PS: Potentially log out of Onecta App on mobile, login again ... if you are asked for new data enter them ... after this should work

**Comment by tziegenbein** [comment]
Hey,I tried to restart but 4 tries didn't bring the objects back. Then I rewrite the credentials and then it worked. I don't know why, nothing changed before. Thank you for your ideas to get back objects. Best regards Tim---------‐-------‐‐-------------Tim Ziegenbein Kohlsberger Höhe 642657 Solingen 0152 ***@***.*** 
-------- Ursprüngliche Nachricht --------Von: Ingo Fischer ***@***.***> Datum: 20.06.24  17:51  (GMT+01:00) An: "Apollon77/ioBroker.daikin-cloud" ***@***.***> Cc: tziegenbein ***@***.***>, Author ***@***.***> Betreff: Re: [Apollon77/ioBroker.daikin-cloud] No object found but 1 Device
  connected (Issue #214) 
PS: Potentially log out of Onecta App on mobile, login again ... if you are asked for new data enter them ... after this should work
