### ISSUE TITLE
Remaining Rate limit as data point

### ISSUE THREAD

**Issue by Volker88** [Apollon77/ioBroker.daikin-cloud#220]
Currently the remaining rate limit is only visible in the debug log.
Would be good to have this also as an data point so we could better see it and trigger actions like notification if it's getting close to 0 etc.

**Comment by Apollon77** [comment]
Good Idea. I will add

**Comment by gahujipo** [comment]
By the way. It seems that the calculation of the retry seconds is not 100% correct (see first line). This would be 15 days. 
![immagine](https://github.com/Apollon77/ioBroker.daikin-cloud/assets/26710574/50fbbf13-38c9-4312-bfbd-edda054d4be0)

And is the polling interval warning always there? Because with an interval of 520 seconds i would have 167 requests per day.

**Comment by Apollon77** [comment]
The value for "retry after "comes from Daikin. I will write them

167 means you only have 33 calls left to control your device and each "control" uses 2 calls (at least - 1x write, 1x read), so you have 16 control operations in 24h left ... is that sufficient for you really?

**Comment by Volker88** [comment]
I just had a look at the logs and found that i have multiple different entries for "RemainingDay". Is this limit for each of my air contitioning units different or is there one limit for all together?


![image](https://github.com/Apollon77/ioBroker.daikin-cloud/assets/47064750/2b1ed45f-9ed5-434b-9d22-953c5a94dbf2)

**Comment by Apollon77** [comment]
Normally "all together", but I also do not know how they exactly calculate the limit ... could also be a moving window or such.

**Comment by gahujipo** [comment]
> The value for "retry after "comes from Daikin. I will write them
> 
> 167 means you only have 33 calls left to control your device and each "control" uses 2 calls (at least - 1x write, 1x read), so you have 16 control operations in 24h left ... is that sufficient for you really?
> 
> And honestly 500s vs 520s does not make too much difference.
> 
> But ok I change that to be an info log ... but ok I will adjust the limit here to 500

Of course you're absolutely right. I didn't realize that each control creates 2 requests: 1x write, 1x read. I'll go with a 900 intervall for the moment.

**Comment by Apollon77** [comment]
please try 0.4.1 from GitHub

**Comment by Apollon77** [comment]
@gahujipo Can you please send me your client id you received this very high number with? Daikin guys would like to look into it

**Comment by gahujipo** [comment]
dMb8hKfz09L8IYCY7tNXecby

**Comment by Apollon77** [comment]
Thanks, I asked Daikin to check why it was that long
