### ISSUE TITLE
While locked out because of rate limit: warning that token is missing

### ISSUE THREAD

**Issue by gahujipo** [Apollon77/ioBroker.daikin-cloud#221]
**Describe the bug**  
Every restart of the instance gives me this warning in the log:
```No tokens existing, please enter client id and secret of your Daikin Developer Account in Adapter settings and Authenticate via Admin Interface!```

I already made the OIDC login and everything worked, but currently I am locked out because of the rate limit on the daikin side.

**To Reproduce**  
 Simply restart the instance. 

**Expected behavior**  
Suppress this warning because this warning is misleading because the credentials are saved. For me this seems as there is somethin wrong in the configuration, but it is only the rate limit. 

```
2024-07-05 14:03:00.853  - info:  daikin-cloud.0 (276765) starting. Version 0.4.1 (non-npm:  Apollon77/ioBroker.daikin-cloud#835b03f2db94585659b8e0fbc9c3becc76efa9fc)  in /opt/iobroker/node_modules/iobroker.daikin-cloud, node: v18.20.3,  js-controller: 5.0.19
--
2024-07-05 14:03:01.045  - debug: daikin-cloud.0 (276765) Rate Limit Status: {"limitMinute":20,"remainingMinute":18,"limitDay":200,"remainingDay":0}
2024-07-05 14:03:01.045  - warn: daikin-cloud.0 (276765) Error on Daikin Cloud communication: API request rate-limited, retry after 706550 seconds
2024-07-05 14:03:01.046  - info: daikin-cloud.0 (276765) Daikin token updated in adapter configuration ...
2024-07-05 14:03:01.050  - info: daikin-cloud.0 (276765) Token seems to be invalid, try automatic re-login ...
2024-07-05 14:03:01.053  - warn:  daikin-cloud.0 (276765) No tokens existing, please enter client id and  secret of your Daikin Developer Account in Adapter settings and  Authenticate via Admin Interface!
```

**Versions:**  
 - Adapter version: 0.4.1
 - JS-Controller version: 5.0.19
 - Node version: v18.20.3
 - Operating system: linux

**Additional context**  
As mentioned earlier I am currently locked out by the rate limit. Maybe this leads to this warning too?

**Comment by Apollon77** [comment]
Ok, it really clears the tokens on such an error ... I will fix it

**Comment by Apollon77** [comment]
Ok, try 0.4.2 .. you need to authenticate anew once but ideally after this the adapter should use the retryAfter time to wait with init

**Comment by gahujipo** [comment]
Now it looks like this. I think this means the issue is solved. 
<img width="1223" alt="image" src="https://github.com/Apollon77/ioBroker.daikin-cloud/assets/26710574/0548c5d8-ce3b-47e6-9b49-913da0e31f6e">

I'll tell you in 14 days (1274867) if it works... I don't really get why I have been locked out for such a long time...

**Comment by Apollon77** [comment]
We learned in the meantime that it seems that requests are counted even when rate limited. That means you (or most likely the adapter because of that issue? Or a combination) did do requests worth 15 days :-(
I sent your client ID to daikin ... lets see if they can do anything here.

**Comment by Apollon77** [comment]
@gahujipo Try to keep adapter off for at least 24h (maybe lets say 36h?) and try again then ... does it then work again?

**Comment by gahujipo** [comment]
Even with the newest version?

**Comment by Apollon77** [comment]
It is about your rate limit. In fact they calculate the request of the currrent day and "weighted" from the day before. You had 3000 the day before and this lead to such a high number.
In theory that calculation should kind of reset after 24h ... latest after48h

**Comment by Apollon77** [comment]
@gahujipo Did yiu tried to leave it off for a day? Works it again?

**Comment by Apollon77** [comment]
Hi,
ok the fact that it started with 170 could be due to the fact that still some "old trx" are somehow calculated in. In fact you can say that each time rate limt info is updated or logged also a request was sent, also mainly following a "Send state change" for "Non polling" reasonse

so with checking "Rate Limit Status:" log lines you can see how it behaves. Each "set" action uses two requests (write, read 1min later).

But yes when you look at
> 2024-07-10 14:07:12.391 - info: daikin-cloud.0 (624802) Send state change for 59710e0d-9c02-489f-897c-c0b531a585d0.climateControl.powerfulMode with value=on to climateControl : powerfulMode : undefined

Then you see that this is called several times without any change in between, so make sure that no mqtt or such pushs "same values" here! I could add a warning in such cases, but it is hard toi know if it is intended or not because it could be that the device was changed via the IR as example and even without data being updated in next polling interval you want to turn it off now

**Comment by Apollon77** [comment]
https://github.com/Apollon77/ioBroker.daikin-cloud/issues/226

**Comment by gahujipo** [comment]
>  I could add a warning in such cases, but it is hard toi know if it is intended or not because it could be that the device was changed via the IR as example and even without data being updated in next polling interval you want to turn it off now

I understand that. But if you think at the setpoint on the IR, that sends the new setpoint only when there is a change of the setpoint compared to the previous value on the remote, regardless of the real setpoint on the indoor unit. Your adapter has the advantage that it retrieves the current value at least with the next polling.

**Comment by Apollon77** [comment]
Please try 0.4.8 ... there it should be prevented to send same values
