### ISSUE TITLE
Warning daikin-cloud has an invalid jsonConfig

### ISSUE THREAD

**Issue by goliat0815** [Apollon77/ioBroker.daikin-cloud#222]
since i installed the new adapter, i see the following warnings in my logfiles:

admin.0 | 2024-07-05 17:03:08.874 | 
warn | 
daikin-cloud has an invalid jsonConfig: [{"instancePath":"/items/_authenticate","schemaPath":"#/definitions/sendToProps/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"window"},"message":"must NOT have additional properties"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"else"},"message":"must match \"else\" schema"}]

**Comment by Apollon77** [comment]
Yes thats an issue in the json schema of jsonconfig

**Comment by Apollon77** [comment]
duplicate https://github.com/ioBroker/ioBroker.admin/issues/2538
