### ISSUE TITLE
Objekte für Econo, Streamer und Intelligentes Sensorauge sind nicht vorhanden

### ISSUE THREAD

**Issue by darktwo2** [Apollon77/ioBroker.daikin-cloud#223]
**Describe the bug**  
Seit der API Umstellung und dem neuen Adapter sind die Objekte für die Funktionen Econo, Streamer und Intelligentes Sensorauge nicht mehr vorhanden. 
Vorher waren diese Objekte unterhalb der jeweiligen Anlage zu finden (climateControl.intelligentEyeMode / climateControl.streamerMode / climateControl.econoMode)

Der PowerfullMode hingegen ist vorhanden.

**To Reproduce** 
 
bei jedem Adapterstart sind die Daten nicht vorhanden

**Expected behavior**  
Sofern Daikin diese Daten liefert sollten sie wieder in den Objekten vorhanden sein

**Screenshots & Logfiles**  
[daikin.log](https://github.com/user-attachments/files/16111280/daikin.log)

<img width="1748" alt="Daikin" src="https://github.com/Apollon77/ioBroker.daikin-cloud/assets/109545053/cc33890e-5ca5-44aa-a605-b5cd83c806c8">

**Versions:**  
 - Adapter version: 0.4.3
 - JS-Controller version: 6.0.6
 - Node version: v18.20.3
 - Operating system: Docker (buanet/iobroker.docker v9.1.2)

**Comment by Apollon77** [comment]
Data no longer provided by Daikin,

**Comment by Apollon77** [comment]
Ok, that seems to be "as designed" for now .. you can just use the chance to write Daikin via the Portal email to request the access and tell why it is needed also as a "Consumer"

**Comment by darktwo2** [comment]
ok, danke

**Comment by Apollon77** [comment]
Ich hab hier mal zu gemacht weil generell ja gelöst
