### ISSUE TITLE
Objects (channel and states) are not created - Occurs when installing or updating the adapter from Github

### ISSUE THREAD

**Issue by Armilar** [Apollon77/ioBroker.daikin-cloud#224]
Preliminary remark: I only have a Daikin Altherma and no other devices

**Occurs when installing or updating the adapter from Github**

Objects (channels and states) are not created. Objects are only created when the instance is restarted.

The objects are deleted and thus relationships to other tools such as InfluxDB, etc. are also permanently deleted and must be created again each time.

![image](https://github.com/Apollon77/ioBroker.daikin/assets/102996011/b9d035f8-8840-412a-95e8-0f0e2c6505c0)

Only when the instance is restarted are the objects recreated

![image](https://github.com/Apollon77/ioBroker.daikin/assets/102996011/92c85ab5-8880-4d50-817c-170d8a5c02e5)

In the lower log (last entry) you can see that the data point "lastUpdateReceived" is deleted. Since this of course causes warnings afterwards, I create it again manually as state/date

see:
![image](https://github.com/Apollon77/ioBroker.daikin/assets/102996011/7533a3cb-bc5a-4d8e-91f6-c6eb101218ae)

[Debug Log ioBroker Daikin Cloud.txt](https://github.com/user-attachments/files/16125862/Debug.Log.ioBroker.Daikin.Cloud.txt)

**Comment by Apollon77** [comment]
Nice one ... Bittte GitHub ausporbieren. Sollte gefixt sein

**Comment by Armilar** [comment]
I tested it briefly. It works

The version number is still 0.4.6?

lastUpdateReceived is no longer there? It was always cool to see when the last update was made

**Comment by Apollon77** [comment]
ooohhh waitt ... forgot to push .. uups ... try again please

**Comment by Armilar** [comment]
hmm
![image](https://github.com/Apollon77/ioBroker.daikin-cloud/assets/102996011/24513468-d4c2-4713-97bf-a2f2148c6be2)

I'll wait a few more minutes and then do it again

**Comment by Armilar** [comment]
* With the last update, last Update Received was created
* The data point cloudConnected, does it have a deeper meaning? It is actually always set to "null"

![image](https://github.com/Apollon77/ioBroker.daikin-cloud/assets/102996011/91def66b-61d5-458d-a4f1-28155a826d7e)

I've done the update a few more times now. It's still version 0.4.6

![image](https://github.com/Apollon77/ioBroker.daikin-cloud/assets/102996011/343963d1-cd24-4001-bf3d-3fd8021e67e8)

**Comment by Armilar** [comment]
![image](https://github.com/Apollon77/ioBroker.daikin-cloud/assets/102996011/56f218cc-ed11-4dc1-87a8-928d4ab2794a)

Incidentally, it also shows in three places that version 0.4.6 is the last one...

Last change included (main.js / README.md

**Comment by Armilar** [comment]
I'll close the issue then ;-) . Everything seems to be working now

Thank you very much
