### ISSUE TITLE
Authorisation not possible after update

### ISSUE THREAD

**Issue by adnet-solutions** [Apollon77/ioBroker.daikin-cloud#225]
i updated the adapter to the latest release.
i followed the setup guide. As i not use https for admin normaly i also created a secon instance of admin adapter.
But i cant authorise to daikin cloud. i get error message that something gioes wrong.
See attached screenshot. Any idea how to solve?
<img width="588" alt="daikinerror" src="https://github.com/Apollon77/ioBroker.daikin-cloud/assets/44036062/5fc3aeec-40c2-42a5-98ec-43260e09ee38">

**Comment by luebke01** [comment]
Kommt der Fehler direkt beim ersten Anmelden, oder erst nach dem Du die App bereits erstellt hast?
Bei mir kam die gleiche Fehlermeldung als ich den 5. Punkt der Anleitung übersehen habe
"5. Redirect-URL aus dem vorherigen Schritt in die App im Daikin Developer Portal eintragen!"
Redirect URL aus dem Popupfenster in die Daikin-App (link ganz oben in der Anleitung) eintragen und mit Punkt 7 weitermachen

**Comment by Apollon77** [comment]
HTTPS Im Admin aktiviert und genutzt?

**Comment by Apollon77** [comment]
>  Gibt es eigentlich die Möglichkeit gegen Bezahlung die 200 Requests zu erweitern?

Ich kenne bisher keine. Aber vllt ist es eine Idee diese Frage an Daoikimn zu stellen und damit die Bereitschaft zu zeigen
