### ISSUE TITLE
Umstellung Onecta App auf Daikin Developer Account

### ISSUE THREAD

**Issue by marcobobinger** [Apollon77/ioBroker.daikin-cloud#229]
Nach der Umstellung von Onecta auf den Daikin Developer Account funktioniert die Anmeldung über den daikin-cloud Adapter wie zu erwarten war nicht mehr.
Ich habe nun einen Daikin Developer Account erstellt und bräuchte ClientID und ClientSecret. Das Konzept ist mir von anderer Stelle bekannt. Wie füge ich meine Daikin Wärmepumpe dem Entwickler-Account hinzu?

**Comment by leost77** [comment]
IoBroker daikin-cloud Adapter v0.4.8 hat bei mir mit WP funktioniert. Wie "jwillemsen" schon beschrieben hat- gleiche Daikin-ID für ONECTA-APP und DAIKIN DEVELOPER ACCOUNT. Es müssen die vorhandenen Daikin-Geräte nicht nochmal im DAIKIN DEVELOPER ACCOUNT angegeben werden.
Iobroker admin.0 auf HTTPS umstellen. Zugriff im Browser dann nur noch mit <https://<yourIP>:8081>
Oder 2 ten admin (admin.1) laden mit:
"verschlüsselte Verbindung HTTPS" aktiv; defaultPublic; defaultPrivate; Chained Zertifikat<kein>.
Port dann bei 2 tem "admin.1"  anstatt 8081 z.B. 8089
update im iobroker auf bei mir v0.4.8. Dann die Anweisung bei Instanz "daikin-cloud.0 --Einstellungen" genau befolgen.
So hat es bei mir funktioniert!

**Comment by Apollon77** [comment]
The Admin panel contains all information. Please look there, create a Daikin Developer account, create a client there and there you get the details
