### ISSUE TITLE
Create App Access not working

### ISSUE THREAD

**Issue by daendaen** [Apollon77/ioBroker.daikin-cloud#234]
Hi,

I wanted to create an app access in the developer area to obtain a Client ID and Client Secret.
However, I’m receiving the following error message:

"Unable to create DCR from HTTP Invalid response: Error: invalid dcr http response"

Can anyone help?

Best regards

**Comment by Apollon77** [comment]
Please contact Daikin via the email available in the Daikin developer portal.

**Comment by jwillemsen** [comment]
Also users of the daikin_onecta integration have this problem, see https://github.com/jwillemsen/daikin_onecta/issues/279

**Comment by kimukao1** [comment]
same here...

**Comment by Apollon77** [comment]
See also https://daikincloudsolutions.statuspage.io/

**Comment by manfred-hofmann** [comment]
Apps können nun wieder erzeugt werden.

**Comment by Apollon77** [comment]
Danke
